# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description_creator',
        ),
    ]
